### ISSUE TITLE
Tips for acquiring tokens

### ISSUE THREAD

**Issue by v0iden** [prasanth-G24/Imdb_to_JustWatch#2]
I had some trouble trying to find the required tokens for the program. Here's how I ended up doing it, for anyone else that might be interested. 

1. open a movie on justwatch, let the site load fully
2. Open DevTools (in Edge, not sure how similar this is for Chrome) with Ctrl+shift+i
3. Go to **Network** at the top
4. Add the movie to your watchlist. 
5. You should see something like the picture below: 
![devtools](https://user-images.githubusercontent.com/31285047/154126572-5c40603a-5e19-46c4-9df7-ebdc1dccb068.png)

**Comment by prasanth-G24** [comment]
thank you for pointing out. will update this in readme.
