### ISSUE TITLE
I am unable to find the request with Status Code 204

### ISSUE THREAD

**Issue by Jonagesh** [prasanth-G24/Imdb_to_JustWatch#3]
As noted in steps, I am unable find the 204 status code in Dev Tools for Just Watch.

Please advise if you are planning to fix the issue

**Comment by prasanth-G24** [comment]
@Jonagesh there has been some recent changes in justwatch site. i am revamping the entire thing. will post an update shortly.

**Comment by prasanth-G24** [comment]
@Jonagesh the token can be obtained from any graphql request. refer this 
![image](https://github.com/user-attachments/assets/3290ef44-c974-4197-bef6-7aff19db7d6d)
